add failing test for custom source extensions feature
test fails with this error:

    UnableToResolveError: Unable to resolve module `./a` from `/root/index.jsx`: Directory /root/a doesn't exist

      at UnableToResolveError (packager/src/node-haste/DependencyGraph/ResolutionRequest.js:625:5)
      at ResolutionRequest._loadAsDir (packager/src/node-haste/DependencyGraph/ResolutionRequest.js:585:13)
      at tryResolveSync (packager/src/node-haste/DependencyGraph/ResolutionRequest.js:441:16)
      at tryResolveSync (packager/src/node-haste/DependencyGraph/ResolutionRequest.js:88:12)
      ...